apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  config.toml: |
    inverter_host = "{{ .Values.inverter_host }}"
    update_interval = "{{ .Values.update_interval }}"

    [simple_mqtt]
    host = "{{ .Values.mqtt.host }}"
    port = {{ .Values.mqtt.port }}
    username = "{{ .Values.mqtt.username }}"
    password = "{{ .Values.mqtt.password }}"
    base_topic = "{{ .Values.mqtt.base_topic }}"
