apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
stringData:
  config.yaml: |
    {{- with .Values.hms_mqtt }}
    {{ toYaml . | nindent 4 }}
    {{- end }}

